default-steps: &default-steps
  - checkout

  - run:
      name: "Init submodules"
      command: git submodule update --init

  - run:
      name: "Configure"
      command: |
        mkdir -p build && cd build
        cmake .. -G "${GENERATOR}" -DCOVERAGE=ON
        echo $CXX > compiler

  - cache-restore:
      name: "Restore dependencies cache"
      key: &deps-cache-key deps-0-{{ checksum "build/compiler" }}-{{ checksum "cmake/ProjectJsonRpcCpp.cmake" }}

  - run:
      name: "Upload Hunter cache"
      command: |
        if [ ! "$CIRCLE_PR_NUMBER" ]; then  # Skip forked PRs.
          cmake --build build --target hunter_upload_cache
        fi

  - run:
      name: "Build"
      command: cmake --build build -- -j $BUILD_PARALLEL_JOBS

  - cache-save:
      name: "Save dependencies cache"
      key: *deps-cache-key
      paths:
        - ~/cpp-ethereum/build/deps

  - store_artifacts:
      path: build/eth/eth
      destination: eth

  - cache-restore:
      name: "Restore Ethash DAG file"
      key: ethash-dag0

  - run:
      name: "Test"
      pwd: ~/cpp-ethereum/build
      command: |
        export ETHEREUM_TEST_PATH=~/cpp-ethereum/test/jsontests
        export TMPDIR=/dev/shm
        CTEST_OUTPUT_ON_FAILURE=1 ctest -j8

  - cache-save:
      name: "Save Ethash DAG file"
      key: ethash-dag0
      paths:
        - ~/.ethash/full-R23-0000000000000000

  - run:
      name: "Code coverage"
      pwd: ~/cpp-ethereum/build
      command: |
        bash <(curl -s https://codecov.io/bash) -X fix

version: 2
jobs:

  default-clang5-ninja:
    environment:
      - CXX: clang++-5.0
      - CC:  clang-5.0
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 8
    docker:
      - image: ethereum/cpp-build-env
    working_directory: ~/cpp-ethereum
    steps: *default-steps

  debug-gcc6-ninja:
    environment:
      - BUILD_TYPE: Debug
      - CXX: g++-6
      - CC:  gcc-6
      - GENERATOR: Ninja
      - BUILD_PARALLEL_JOBS: 4
    docker:
      - image: ethereum/cpp-build-env
    working_directory: ~/cpp-ethereum
    steps: *default-steps

  mac:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          command: |
            echo $PATH
            echo $HOMEBREW_PREFIX
            make --version
            python --version
            pip install requests
            brew install cmake ninja leveldb libmicrohttpd
      - run:
          command: |
            echo $PATH
            git submodule update --init --depth 50
            pwd
            ls -l
            mkdir -p build && cd build
            clang --version
            cmake --version
            make --version
            ninja --version
            cmake .. -G Ninja
            cmake --build . --target hunter_upload_cache
            ninja -j8
            ETHEREUM_TEST_PATH=~/project/test/jsontests test/testeth


workflows:
  version: 2
  cpp-ethereum:
    jobs:
      - mac
#      - default-clang5-ninja
#      - debug-gcc6-ninja